# Generated by Django 2.2.12 on 2020-04-17 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_paymentletter_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerOffer',
            fields=[
                ('id', models.CharField(max_length=2056, primary_key=True, serialize=False)),
                ('order', models.CharField(max_length=2056)),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Organization')),
            ],
        ),
    ]
