# Generated by Django 2.2.12 on 2020-04-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_produceroffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=2056)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
