# Generated by Django 2.2.12 on 2020-04-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Organization'),
        ),
    ]
